goldmark:
  renderer:
    unsafe: true

highlight:
  noClasses: false
  anchorLineNos: false
  codeFences: true
  guessSyntax: false
  hl_Lines: ""
  hl_inline: false
  lineAnchors: ""
  lineNoStart: 1
  lineNos: false
  lineNumbersInTable: true
  # noClasses: true
  noHl: false
  style: nord
  tabWidth: 4

tableOfContents:
  startLevel: 2
  endLevel: 4