---
colorScheme: blowfish
defaultAppearance: light
autoSwitchAppearance: true
enableSearch: true
enableCodeCopy: true
disableImageOptimization: false

outputs:
  home:
    - HTML
    - RSS
    - JSON

keywords:
  - Engineering
  - Software Development
  - Tech

list:
  showHero: false
  heroStyle: basic
  showBreadcrumbs: false
  layoutBackgroundBlur: true
  layoutBackgroundHeaderSpace: true
  showTableOfContents: false
  showSummary: true
  showViews: false
  showLikes: false
  showCards: true
  groupByYear: true
  cardView: false

article:
  showDate: true
  showViews: false
  showLikes: false
  showDateOnlyInArticle: false
  showDateUpdated: false
  showAuthor: false
  showHero: true
  heroStyle: big
  layoutBackgroundBlur: false
  layoutBackgroundHeaderSpace: false
  showBreadcrumbs: false
  showDraftLabel: true
  showEdit: false
  # editURL: https://github.com/ludovicwyffels/blog
  editAppendPath: true
  seriesOpened: false
  showHeadingAnchors: true
  showPagination: true
  invertPagination: false
  showReadingTime: true
  showTableOfContents: true
  showRelatedContent: false
  relatedContentLimit: 3
  showTaxonomies: false
  showAuthorsBadges: false
  showWordCount: false
  showComments: false
  sharingLinks: false
  showZenMode: true

homepage:
  layout: profile
  # layout: page
  homepageImage: img/ludo.png
  showRecent: true
  showRecentItems: 5
  showMoreLink: true
  showMoreLinkDest: /blog
  cardView: false
  cardViewScreenWidth: false
  layoutBackgroundBlur: false

taxonomy:
  showSummary: true

term:
  showSummary: true
  showHero: true
  heroStyle: basic

header:
  layout: fixed-fill-blur
  showAppearanceSwitcher: true

footer:
  showMenu: true
  showCopyright: true
  showThemeAttribution: true
  showAppearanceSwitcher: true
  showScrollToTop: true