---
colorScheme: slate
defaultAppearance: light
autoSwitchAppearance: true

enableSearch: true
enableCodeCopy: true
disableImageOptimization: false

outputs:
  home:
    - HTML
    - RSS
    - JSON

keywords:
  - Engineering
  - Software Development
  - Tech

header:
  layout: fixed-fill-blur #valid options: basic, fixed, fixed-fill-blur
  showAppearanceSwitcher: true

footer:
  showMenu: true
  showCopyright: true
  showThemeAttribution: true
  showAppearanceSwitcher: true
  showScrollToTop: true

homepage:
  layout: profile # valid option: page, profile, hero, card, background, custom
  homepageImage: img/ludo2022.webp #used in: hero and card
  showRecent: true
  showRecentItems: 5
  showMoreLink: true
  showMoreLinkDest: /blog
  cardView: false
  cardViewScreenWidth: false
  layoutBackgroundBlur: false

article:
  showDate: true
  # showViews: false
  # showLikes: false
  showDateOnlyInArticle: false
  showDateUpdated: true
  showAuthor: false
  showHero: true
  heroStyle: big # valid optinos: basic, big, background
  showBreadcrumbs: true
  showDraftLabel: true
  showEdit: false
  # editURL: https://github.com/ludovicwyffels/blog
  editAppendPath: true
  seriesOpened: false
  showHeadingAnchors: true
  showPagination: true
  invertPagination: false
  showReadingTime: true
  showTableOfContents: true
  showTaxonomies: false
  showAuthorsBadges: false
  showWordCount: true
  showSummary: true

  showRelatedContent: true
  relatedContentLimit: 3
  
  showComments: false
  showZenMode: true
  # sharingLinks: false
  sharingLinks:
    - linkedin
    - twitter
    - pinterest
    - reddit
    - facebook
    - email

list:
  showBreadcrumbs: false
  showSummary: true
  showTableOfContents: false
  showCards: true
  groupByYear: true
  cardView: false
  cardViewScreenWidth: false
  constrainItermsWith: true

taxonomy:
  showSummary: true

term:
  showSummary: true
  showHero: true
  heroStyle: basic
