# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Deploy Hugo site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy Hugo site to GitHub Pages
    steps:
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.123.8'
      - name: Checkout repo on source_branch
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          fetch-depth: '0'
            
      - name: Build site and push to release branch
        uses: aormsby/hugo-deploy-to-pages@v2.1.1
        with:
          source_branch: 'master'
          release_branch: 'gh-pages'
      - name: Check if new build was made
        if: steps.build.outputs.was_new_build_created == 'true'
        run: echo "YAAASSSS new build."
